language: php

sudo: false

dist: trusty

php:
    - 5.6
    - 7.0
    - 7.3
    - nightly

env:
    - VALIDATOR_VERSION="2.8.*"
    - VALIDATOR_VERSION="5.0.*"

matrix:
    fast_finish: true
    exclude:
        - php: 5.6
          env: VALIDATOR_VERSION="5.0.*"
        - php: 7.0
          env: VALIDATOR_VERSION="5.0.*"
    allow_failures:
        - php: nightly

before_script:
    - mkdir -p build/logs
    - composer require symfony/validator:${VALIDATOR_VERSION} --prefer-dist --no-interaction --no-progress

script:
    - vendor/bin/phpunit -v --coverage-clover build/logs/clover.xml
    - if [ "${TRAVIS_PHP_VERSION}" != 'nightly' ]; then travis_retry wget -q https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar && travis_retry php coveralls.phar -v; fi

notifications:
    email:
        - antalaron@antalaron.hu

cache:
    directories:
        - $HOME/.composer/cache
